version: '3'
services:
  
  devlab-api:
    container_name: devlab-api
    depends_on:
      - devlab-db
    build:
      context: ../
      dockerfile: ./src/Lab.Customers.Api/Dockerfile
    ports:
      - "8080:8080"
  
  devlab-db:
    image: postgres:latest
    container_name: devlab-db
    environment:
      POSTGRES_USER: devlab
      POSTGRES_PASSWORD: devlab
      POSTGRES_DB: devlab
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: