name: Release
on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

permissions:
  contents: read # for checkout

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      
      # Create a temporary package.json file
      - name: Create package.json
        run: |
          echo '{
            "name": "temporary-release",
            "version": "1.0.0",
            "private": true,
            "devDependencies": {
              "semantic-release": "^21.0.0",
              "@semantic-release/changelog": "^6.0.2",
              "@semantic-release/git": "^10.0.0",
              "@semantic-release/github": "^8.0.0",
              "@semantic-release/commit-analyzer": "^10.0.0",
              "@semantic-release/release-notes-generator": "^11.0.0"
            }
          }' > package.json
          
      - name: Install dependencies
        run: npm install
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
